import { useRef } from 'react';
import { Canvas, useFrame, useThree } from '@react-three/fiber';
import { Grid, OrbitControls, PerspectiveCamera, OrthographicCamera, Line, GizmoHelper, GizmoViewport } from '@react-three/drei';
import * as THREE from 'three';
import Neuron from './Neuron';
import type { Memory } from './data';

type Props = { memories:Memory[]; selectedId:string|null; onSelect:(id:string)=>void; onFocus?:(id:string)=>void; cad:boolean; wireframe:boolean; orthographic:boolean; focus:boolean; focusTarget?:string|null; accessed:string[] };
function SceneContent({ memories, selectedId, onSelect, onFocus, cad, wireframe, orthographic, focus, focusTarget, accessed }:Props) { const group=useRef<THREE.Group>(null); const {camera}=useThree(); const selected=memories.find(m=>m.id===selectedId); useFrame((_,delta)=>{ if(group.current&&!focus) group.current.rotation.y+=delta*.012; const target=memories.find(m=>m.id===(focusTarget||selectedId)); if(target){ const next=new THREE.Vector3(...target.position).add(new THREE.Vector3(4,3,4)); camera.position.lerp(next,Math.min(1,delta*2.4)); camera.lookAt(...target.position); } }); const ids=new Set(memories.map(m=>m.id)); return <>
    {orthographic?<OrthographicCamera makeDefault position={[25,18,25]} zoom={22}/>:<PerspectiveCamera makeDefault position={[25,18,25]} fov={48}/>}<color attach="background" args={['#070b12']}/><fog attach="fog" args={['#070b12',25,75]}/><ambientLight intensity={.5}/><directionalLight position={[10,18,8]} intensity={2.2} color="#b8d7ff"/><pointLight position={[-15,4,-15]} intensity={30} distance={35} color="#224b99"/>
    {cad&&<><Grid args={[80,80]} position={[0,-9,0]} cellSize={1} cellThickness={.4} cellColor="#1b4350" sectionSize={5} sectionThickness={.75} sectionColor="#27616d" fadeDistance={55} infiniteGrid/><Line points={[[-22,0,0],[22,0,0]]} color="#e16a6a" lineWidth={1}/><Line points={[[0,-12,0],[0,12,0]]} color="#6be09b" lineWidth={1}/><Line points={[[0,0,-22],[0,0,22]]} color="#6a9dff" lineWidth={1}/></>}
    <group ref={group}>{memories.slice(0,1000).map(m=><Neuron key={m.id} memory={m} selected={m.id===selectedId} dimmed={Boolean(selectedId&&m.id!==selectedId&&!selected?.relations.includes(m.id)&&!m.relations.includes(selectedId))} onSelect={()=>onSelect(m.id)} onFocus={()=>onFocus?.(m.id)} inspect={m.id===selectedId} cad={cad||m.id===selectedId} wireframe={wireframe} accessed={accessed.includes(m.id)}/>)}{selected&&selected.relations.filter(id=>ids.has(id)).map(id=>{const other=memories.find(m=>m.id===id)!; return <Line key={`relation-${id}`} points={[selected.position,other.position]} color="#ffb56b" lineWidth={1.2} transparent opacity={.65} dashed/>;})}</group><OrbitControls makeDefault enableDamping dampingFactor={.08} minDistance={4} maxDistance={65}/><GizmoHelper alignment="bottom-right" margin={[70,70]}><GizmoViewport axisColors={['#ef6b6b','#69d698','#6f9cff']} labelColor="white"/></GizmoHelper>
  </>; }
export default function MemoryScene(props:Props){ return <Canvas dpr={[1,1.5]} gl={{antialias:true,powerPreference:'high-performance'}} onCreated={({gl})=>gl.setPixelRatio(Math.min(window.devicePixelRatio,1.5))}><SceneContent {...props}/></Canvas>; }
