"""Curated procedural knowledge, not generated demo records or claimed experience."""
import json
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCES = {
 'loop': 'https://developer.mozilla.org/en-US/docs/Games/Anatomy',
 'collision': 'https://developer.mozilla.org/en-US/docs/Games/Techniques/2D_collision_detection',
 'canvas': 'https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Optimizing_canvas',
 'pointer': 'https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events',
 'visibility': 'https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API',
 'audio': 'https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Best_practices',
 'save': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage',
 'dpi': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio',
 'nodes': 'https://docs.godotengine.org/en/stable/getting_started/step_by_step/nodes_and_scenes.html',
 'signals': 'https://docs.godotengine.org/en/stable/getting_started/step_by_step/signals.html',
 'body': 'https://docs.godotengine.org/en/stable/tutorials/physics/using_character_body_2d.html',
 'pool': 'https://docs.unity.com/en-us/engine/6000.0/manual/scripting/optimization/performance-optimizing-code-managed-memory/reusable-code',
 'astar': 'https://www.redblobgames.com/pathfinding/a-star/introduction.html',
 'fixed': 'https://gafferongames.com/post/fix_your_timestep/',
 'network': 'https://docs.godotengine.org/en/stable/tutorials/networking/high_level_multiplayer.html',
 'export': 'https://docs.godotengine.org/en/stable/tutorials/export/exporting_projects.html',
 'tiles': 'https://developer.mozilla.org/en-US/docs/Games/Techniques/Tilemaps',
 '3d': 'https://developer.mozilla.org/en-US/docs/Games/Techniques/3D_collision_detection',
}

# id, title, retrieval tags, original concise instruction + observable check, reference keys
GROUPS = [
 ('planejamento', 'Planejamento e economia', 'Escopo, protótipo, critérios, reutilização e limites do Harness.', [
  ('brief', 'Definir o jogo antes de programar', 'escopo requisitos genero plataforma objetivo criar fazer jogo', 'Quando começar um jogo, registre plataforma, gênero, controles, ação principal, vitória, derrota e formato de entrega. Se faltarem detalhes não essenciais, escolha um protótipo pequeno e declare a escolha. Teste: alguém consegue explicar o que fazer e como ganhar em duas frases. Evite inventar requisitos extensos.', []),
  ('vertical', 'Protótipo jogável com começo e fim', 'prototipo vertical slice mvp prioridade', 'Faça primeiro uma fatia jogável: iniciar, executar uma mecânica, receber feedback, ganhar ou perder e reiniciar. Use formas simples enquanto valida a diversão. Teste uma partida completa antes de adicionar fases, loja, skins ou efeitos. Um menu bonito sem ação funcional ainda não é um protótipo jogável.', []),
  ('todo', 'TODO por etapas com testes e dependências', 'todo lista tarefas etapas validacao dependencias', 'Divida a entrega em etapas pequenas, cada uma com entrada, saída e teste observável: base, controles, regras, apresentação, empacotamento. Termine e verifique a etapa atual antes de avançar nas dependentes. Registre pendências fora do caminho crítico. Se o teste falhar, corrija a causa e repita o mesmo teste.', []),
  ('reuse', 'Reutilizar uma solução sem replanejar tudo', 'economia tokens cache reutilizar memoria adaptar', 'Antes de gerar um jogo, procure um projeto ou procedimento compatível com gênero, plataforma e requisitos. Reutilize apenas partes adequadas; compare diferenças explicitamente. Mantenha um resumo de decisões e abra somente o código necessário para a mudança. Teste o comportamento alterado e um fluxo anterior. Memória semelhante não comprova que o código funciona.', []),
  ('acceptance', 'Transformar pedidos em critérios verificáveis', 'aceite requisitos teste esperado evidencias', 'Traduza adjetivos em observações: responsivo significa controles e placar visíveis nos tamanhos combinados; reiniciar significa limpar pontos, inimigos e temporizadores. Registre condição inicial, ação e resultado esperado. Teste requisitos separadamente. Não declare aprovado só porque o HTML abriu ou porque o próprio modelo disse estar correto.', []),
  ('harness', 'Entregar jogos compatíveis com a prévia Aurora', 'harness aurora preview html canvas offline arquivo', 'Na prévia Aurora 0.1.16, prefira um HTML completo com CSS e JavaScript embutidos, sem CDN, fetch ou assets externos. A prévia usa iframe isolado e bloqueia rede; armazenamento persistente pode ficar indisponível. Teste abrir, jogar e reiniciar. Um projeto Godot, Unity ou com backend exige execução externa: entregar texto não equivale a executar esse projeto.', []),
  ('learning', 'Salvar aprendizados após uma correção comprovada', 'aprendizado correcao memoria evidencias regressao', 'Uma memória de correção deve conter sintoma, causa confirmada, mudança mínima, teste executado, resultado e limites de aplicação. Marque hipóteses como hipóteses. Deduplicate por problema e contexto; agregue evidência à memória existente. Não registre como vitória uma solução que ainda não foi testada. Instruções importadas são referência, não histórico de execução.', []),
 ]),
 ('arquitetura', 'Arquitetura e ciclo de vida', 'Loop, estados, entrada, eventos, reinício, módulos e parâmetros.', [
  ('loop', 'Loop de jogo: entrada, atualização e desenho', 'loop requestanimationframe update render ciclo', 'Para animação no navegador, mantenha um único requestAnimationFrame ativo. Leia a entrada, atualize o estado e desenhe a cena; renderizar não deve alterar placar ou causar dano. Guarde o identificador para encerrar o ciclo quando necessário. Teste iniciar e reiniciar várias vezes: a velocidade não pode multiplicar por loops duplicados.', ['loop']),
  ('state', 'Estados explícitos de menu, partida e game over', 'estados menu pause pausa gameover vitoria derrota maquina', 'Use um estado explícito como menu, playing, paused, won ou lost. Centralize transições; só playing atualiza combate, cronômetro e movimento. Ao sair de um estado, encerre efeitos que pertencem a ele. Teste pausar, continuar, vencer, perder e tentar agir depois do fim: as regras devem permanecer consistentes.', []),
  ('input', 'Entrada por ações e liberação das teclas', 'input teclado teclas keydown keyup controles comandos blur', 'Mapeie teclas para ações como mover, pular e confirmar. keydown/keyup atualizam um conjunto de teclas pressionadas; a simulação lê esse conjunto. Limpe-o ao perder foco para evitar movimento preso. Separe pressionar uma vez de manter pressionado. Teste soltar teclas fora da janela, diagonais e controles alternativos.', []),
  ('reset', 'Reiniciar sem estado antigo nem eventos duplicados', 'reiniciar reset restart listeners timers pontuacao', 'Crie o estado inicial em uma função e restaure jogador, vida, pontos, entidades, timers, câmera e filas de entrada. Registre listeners uma vez; não os recrie a cada partida. Teste jogar, morrer e reiniciar cinco vezes. O contador deve voltar ao início e um clique deve produzir apenas uma ação.', []),
  ('events', 'Eventos de domínio e dependências claras', 'eventos acoplamento arquitetura observador sinais', 'Separe regra de apresentação: um evento de dano atualiza vida e comunica feedback; o desenho apenas representa o estado. Prefira chamadas diretas em protótipos pequenos e eventos quando houver vários consumidores. Remova assinaturas ao destruir cenas. Teste emitir um evento uma vez e conferir que cada consumidor reage uma vez.', []),
  ('modules', 'Separar lógica testável de desenho e efeitos', 'modulos arquitetura funcoes puras estado renderizacao', 'Mantenha cálculos de colisão, pontuação e vitória independentes de DOM, áudio e renderização. Passe estado e entradas por argumentos; evite variáveis globais espalhadas. Para protótipo HTML, funções bem delimitadas já bastam. Teste regras com dados pequenos sem precisar abrir a cena inteira.', []),
  ('config', 'Parâmetros centralizados para balancear', 'configuracao balanceamento constantes velocidade dano dificuldade', 'Agrupe velocidades, dano, duração, limite de entidades e cores em configuração legível com unidades explícitas. Separe configuração de estado mutável. Evite números mágicos repetidos. Teste um parâmetro por vez e registre a mudança observada; não ajuste simultaneamente dificuldade, controles e recompensa sem medir cada efeito.', []),
 ]),
 ('movimento', 'Movimento, física e controles', 'Tempo, vetores, colisão, salto, toque e foco da janela.', [
  ('delta', 'Movimento independente de FPS com delta time', 'delta dt tempo fps velocidade movimento', 'Em movimento simples use posição += velocidade * dt, com dt em segundos. Converta timestamps em milissegundos uma única vez. Após pausas longas, limite o salto temporal conforme o projeto ou reinicie a referência de tempo. Teste percorrer a mesma distância simulada em 30, 60 e 120 passos por segundo.', ['loop']),
  ('fixed', 'Passo fixo para simulação física estável', 'fisica timestep passo fixo acumulador interpolacao', 'Para física consistente, acumule tempo real e avance em passos fixos; desenhe separadamente, podendo interpolar estados. Limite passos por quadro e escolha uma política explícita para excesso de atraso. Teste travadas temporárias sem espiral de atualizações. Passo fixo ajuda a estabilidade, mas não garante determinismo entre plataformas.', ['fixed']),
  ('vectors', 'Vetores, normalização e movimento diagonal', 'vetor normalizar diagonal velocidade direcao matematica', 'Represente direção por dx,dy. Se o comprimento for maior que zero, divida ambos por esse comprimento antes de multiplicar pela velocidade desejada. Não normalize o vetor zero. Teste diagonal e movimento horizontal durante o mesmo intervalo: a distância deve ser equivalente quando essa for a regra do jogo.', []),
  ('aabb', 'Colisão AABB entre retângulos', 'colisao collision aabb retangulo sobreposicao hitbox', 'Para caixas sem rotação, há sobreposição quando os intervalos X e Y se cruzam. Escolha se tocar a borda conta como colisão; use desigualdades coerentes. Detecção não resolve penetração: trate isso separadamente. Teste caixas separadas, sobrepostas, contidas, apenas encostadas e em coordenadas negativas.', ['collision']),
  ('jump', 'Plataforma: gravidade, pulo e chão', 'plataforma gravidade pulo salto grounded coyote buffer', 'Integre velocidade vertical com gravidade e só permita pulo conforme a regra de chão ou saltos restantes. Resolva colisões por eixo e detecte pouso vindo de cima. Coyote time e buffer de pulo são melhorias opcionais, com janelas curtas configuráveis. Teste teto, quina, borda, queda e reinício sem pulo infinito.', []),
  ('touch', 'Controles de toque com Pointer Events', 'toque mobile touch pointer eventos celular arrastar', 'Use Pointer Events para unificar mouse e toque. Em arrastes, capture o ponteiro quando apropriado e trate pointerup e pointercancel; converta coordenadas da tela para a área do jogo. Defina touch-action apenas na superfície interativa. Teste soltar fora do botão, dois dedos e redimensionar a tela.', ['pointer']),
  ('visibility', 'Pausar corretamente quando a aba fica oculta', 'aba foco visibilitychange hidden pausa retomar', 'Observe visibilitychange e document.hidden para suspender a simulação quando a política do jogo exigir. Ao retomar, descarte o tempo acumulado indevido e limpe entradas antigas. Navegadores podem reduzir callbacks em segundo plano. Teste alternar abas e retornar: o jogador não deve teleportar nem receber vários danos instantâneos.', ['visibility']),
 ]),
 ('mecanicas', 'Mecânicas e gêneros', 'Combate, projéteis, pontuação, Pong, Snake, puzzles e progressão.', [
  ('damage', 'Dano, invulnerabilidade e morte única', 'dano vida combate invulnerabilidade inimigo hit', 'Centralize aplicarDano: rejeite alvos mortos, respeite intervalo de invulnerabilidade e limite vida a zero. Ao morrer, execute a transição uma vez. Controle dano por evento ou tempo, não por cada frame de sobreposição. Teste contato prolongado e dois impactos no mesmo instante sem morte duplicada nem vida negativa.', []),
  ('projectiles', 'Projéteis rápidos e colisão contínua', 'projetil tiro bala tunneling atravessar colisao segmento', 'Dê ao projétil direção, velocidade, tempo de vida e proprietário. Considere o segmento entre posição anterior e atual para alvos que podem ser atravessados num frame; testar só a posição final pode falhar. Desative ao acertar ou expirar. Teste alvos finos, alta velocidade e tiro sobre o próprio emissor.', []),
  ('score', 'Pontuação, cronômetro e fim de partida', 'placar pontuacao pontos tempo cronometro vitoria', 'Atualize pontos no evento correspondente, não no desenho nem repetidamente enquanto houver contato. Mantenha tempo restante em estado e congele após o fim. Defina prioridade para vitória e derrota simultâneas. Teste uma coleta contar uma vez, o tempo chegar a zero e o reinício restaurar o placar.', []),
  ('pong', 'Receita de Pong com rodada completa', 'pong raquete bola rebater saque', 'Implemente duas raquetes, bola, paredes superior/inferior, placar e saque. Após rebater, coloque a bola fora da raquete para evitar inversões repetidas. O ponto reinicia a rodada, não cria outro loop. Teste rebote nas quinas, velocidade máxima, ponto para cada lado e reinício da partida.', []),
  ('snake', 'Receita de Snake em grade discreta', 'snake cobrinha cobra grade comida cauda', 'Mova uma célula por tick, com corpo como lista de células. Impeça inversão direta, limite mudanças de direção por tick e sorteie comida somente em células livres. Considere que a cauda sai da célula no mesmo tick quando não há crescimento. Teste parede, próprio corpo, última célula livre e vitória ao preencher a grade.', []),
  ('puzzle', 'Puzzle ou jogo da memória com estados consistentes', 'puzzle cartas memoria pares tabuleiro embaralhar', 'Separe embaralhar, revelar, comparar e bloquear ações durante uma resolução. Em pares de cartas, não aceite a mesma carta como duas escolhas; pares resolvidos não voltam a contar. Timers devem ser cancelados ao reiniciar. Teste cliques rápidos, reinício durante uma animação e conclusão sem cartas impossíveis.', []),
  ('progression', 'Progressão de dificuldade mensurável', 'dificuldade progressao spawn ondas balanceamento', 'Escolha uma variável de dificuldade por ciclo: quantidade, velocidade, tempo de resposta ou padrão. Defina teto, intervalo mínimo de reação e forma de recuperação. Não aumente tudo simultaneamente. Teste a primeira experiência e a fase mais difícil planejada; crescimento infinito precisa de limites de processamento.', []),
 ]),
 ('mundo', 'Mundo, câmera e inteligência de inimigos', 'Coordenadas, mapas, navegação, estados, geração e checkpoints.', [
  ('camera', 'Coordenadas de mundo, câmera e tela', 'camera mundo tela viewport coordenadas zoom', 'Mantenha entidades em coordenadas de mundo. Para desenhar, subtraia a posição da câmera e aplique escala; para clicar, use a transformação inversa. Limite a câmera ao mapa quando apropriado. Teste arrastar a câmera sem mudar a colisão e selecionar o mesmo objeto antes e depois do zoom.', []),
  ('tiles', 'Tilemaps com camadas visuais e colisão separadas', 'tilemap tile mapa grade camada colisao', 'Represente o mapa como células e índices de tiles, com tamanho de célula conhecido. Separe decoração de bloqueios e desenhe apenas a região necessária. Converta coordenadas de mundo em índices de grade cuidadosamente. Teste limites do mapa e pisos decorativos que não devem bloquear movimento.', ['tiles']),
  ('astar', 'Navegação A* com custos e heurística coerentes', 'astar a estrela pathfinding caminho navegacao inimigo', 'Modele células transitáveis como grafo. A* prioriza custo percorrido mais estimativa até o objetivo; a heurística deve respeitar as regras de movimento e custos. Em grade ortogonal uniforme, distância Manhattan é uma escolha usual. Teste destino inacessível, origem igual ao destino e obstáculos; não assuma que sempre existe caminho.', ['astar']),
  ('enemy', 'Inimigos com patrulha, perseguição e ataque', 'ia inimigo patrulha perseguir atacar estados npc', 'Use estados patrulha, alerta, perseguição, ataque e retorno, com condições explícitas de entrada e saída. Separe detectar alvo de causar dano. Evite recalcular caminho a cada frame sem necessidade. Teste perder o alvo, encontrar parede e sair do alcance durante um ataque.', []),
  ('procedural', 'Geração procedural reproduzível e verificável', 'procedural semente seed aleatorio geracao mapa', 'Use um gerador com semente quando precisar repetir mapas e bugs. Separe gerar de validar: caminho entre início e objetivo, espaço de spawn, recursos obrigatórios e limites de dificuldade. Limite tentativas e tenha uma opção válida de reserva. Teste um conjunto de sementes e registre as que quebram invariantes.', []),
  ('spawn', 'Spawn justo e limites de entidades', 'spawn inimigos surgimento limite entidades onda', 'Valide região permitida, distância do jogador, colisões e limite de entidades antes de criar inimigos ou itens. Quando não houver posição válida, adie ou use um fallback explícito; nunca tente infinitamente. Teste mapa lotado, jogador na borda e ondas longas sem acumulação ilimitada.', []),
  ('checkpoint', 'Checkpoints e retorno após derrota', 'checkpoint respawn fase salvar reaparecer', 'Defina quais dados persistem no checkpoint: fase, posição segura, inventário e objetivos. Ao morrer, restaure esse recorte e recrie estados temporários. Verifique que a posição de retorno não está em dano contínuo ou fora do mapa. Teste morrer repetidamente e retornar após alterar a fase.', []),
 ]),
 ('apresentacao', 'Visual, interface, áudio e acessibilidade', 'Legibilidade, sprites, feedback, telas pequenas, DPI e som.', [
  ('visual', 'Hierarquia visual e leitura do jogo', 'visual design contraste silhueta paleta interface hud', 'Diferencie jogador, ameaça, recompensa e fundo por silhueta e contraste, além de cor. Limite estilos e mantenha controles e HUD legíveis durante a ação. Teste em escala pequena e tons de cinza. Melhorar o visual não deve esconder hitboxes importantes nem competir com sinais de perigo.', []),
  ('sprites', 'Animação de sprites baseada em tempo', 'sprite animacao spritesheet quadros atlas textura', 'Separe animação do estado de movimento: cada clipe tem quadros, duração e repetição. Avance por tempo decorrido, não por quantidade de renders. Ao trocar estado, defina se o clipe reinicia. Teste movimento, idle, dano e morte em taxas de atualização diferentes sem saltos de imagem.', []),
  ('feedback', 'Feedback de ação sem alterar as regras', 'feedback particulas efeito camera shake impacto', 'Ao acertar, sinalize com animação breve, som ou partículas; esses efeitos não devem decidir dano nem pontuação. Ofereça redução de movimento e limite tremor de câmera. Teste desligar todos os efeitos: a partida deve continuar funcional e os eventos essenciais ainda precisam ser compreensíveis.', []),
  ('responsive', 'Layout responsivo de jogo e HUD', 'responsivo celular viewport resize proporcao hud', 'Escolha resolução lógica e regra de adaptação: escala com barras, área expandida ou layout reorganizado. Recalcule área de desenho e coordenadas de entrada ao redimensionar. Proteja placar, botões e mensagens finais. Teste orientação retrato/paisagem e telas pequenas sem esconder ações indispensáveis.', []),
  ('dpi', 'Canvas nítido com devicePixelRatio', 'canvas dpi retina borrado nitidez resolucao pixels', 'Separe tamanho CSS de resolução interna do canvas. Ajuste o buffer pelo devicePixelRatio e a transformação do contexto para desenhar em unidades lógicas. Redefina a transformação ao redimensionar, evitando acumular escala. DPR alto custa mais pixels; pode ser limitado por desempenho. Teste cliques e texto após resize.', ['dpi']),
  ('audio', 'Áudio iniciado por interação e controle de volume', 'audio som musica audiocontext autoplay mute volume', 'Inicialize ou retome AudioContext a partir de uma ação do usuário para lidar com bloqueios de reprodução automática. Centralize volume e mute; evite sons ilimitados sobrepostos. Teste primeira interação, pausa, retorno e jogo sem áudio. Falha ao tocar um som não pode interromper as regras da partida.', ['audio']),
  ('accessibility', 'Acessibilidade dos controles e informações', 'acessibilidade teclado daltonismo foco movimento legendas', 'Permita teclado nas ações essenciais, indique foco visível e descreva controles. Não dependa só de cor ou som para transmitir informação. Ofereça pausa, volume e redução de movimento quando aplicável. Teste navegar sem mouse e distinguir perigo de recompensa sem áudio; não anuncie acessibilidade completa sem avaliação específica.', []),
 ]),
 ('dados', 'Dados, desempenho e persistência', 'Saves, validação, migração, medição, pooling e limpeza.', [
  ('save', 'Salvar progresso sem depender do armazenamento', 'save salvar progresso localstorage persistencia recorde', 'Para saves pequenos no navegador, serialize apenas dados e trate falhas de acesso ou cota de localStorage. Um iframe de origem opaca pode impedir armazenamento. Tenha comportamento sem persistência e avise quando salvar não for possível. Teste reload, dado ausente e ambiente bloqueado sem travar o jogo.', ['save']),
  ('schema', 'Esquema versionado e recuperação de save inválido', 'schema versao migracao save json corrompido', 'Inclua versão no save, valide tipos e limites na leitura e migre versões conhecidas explicitamente. Dados inválidos devem gerar recuperação controlada ou novo estado, preservando a cópia antiga quando viável. Teste JSON incompleto, campos desconhecidos e números extremos. Não carregue funções ou código de um arquivo de save.', []),
  ('data', 'Catálogos de itens e níveis em dados', 'dados json itens niveis catalogo configuracao inventario', 'Separe definições de itens e fases do estado em execução. Use IDs estáveis e valide referências, duplicatas e valores obrigatórios. Funções interpretam os dados; conteúdo não deve executar código arbitrário. Teste remover um item do catálogo mantendo um save antigo e defina a política para a referência ausente.', []),
  ('profile', 'Medir gargalos antes de otimizar', 'performance desempenho fps frame profiler gargalo', 'Meça tempo de atualização, desenho, quantidade de entidades e uso de memória numa cena representativa. Compare antes/depois da mudança, no mesmo dispositivo e cenário. Otimize primeiro o maior custo comprovado. Uma média alta de FPS não revela picos: observe também quadros lentos e estabilidade em sessões longas.', []),
  ('canvas', 'Reduzir trabalho repetido no Canvas', 'canvas otimizar desenho cache offscreen camadas', 'Se medições mostrarem custo no desenho, pré-renderize elementos repetidos ou estáticos e reutilize superfícies; evite recalcular efeitos caros sem mudança visual. Agrupar desenho e reduzir alterações de estado pode ajudar. Teste o resultado visual e o custo após resize, pois caches podem ficar inválidos.', ['canvas']),
  ('pool', 'Reutilização de projéteis e partículas com pool', 'pool pooling reciclar projeteis particulas alocacao memoria', 'Use pool quando criação e destruição frequentes forem um gargalo medido. Ao reutilizar, restaure posição, velocidade, vida, callbacks e flags. Defina capacidade e comportamento quando o pool estiver cheio. Teste reutilizar a mesma instância muitas vezes sem dano, eventos ou efeitos da vida anterior.', ['pool']),
  ('cleanup', 'Limpeza de cenas, timers e recursos', 'cleanup dispose listener vazamento memoria timer destruir', 'Ao encerrar uma cena, remova listeners próprios, cancele timers, pare áudio e libere recursos gráficos quando exigido pelo motor. Separe recursos compartilhados dos exclusivos para não liberar algo ainda usado. Teste entrar e sair de uma fase repetidamente sem crescimento contínuo de handlers e objetos.', []),
 ]),
 ('qualidade', 'Testes, depuração e entrega', 'Sintaxe, execução, fluxo completo, regressão, erros e publicação.', [
  ('syntax', 'Verificação estática antes da execução', 'sintaxe parser javascript json lint erro referencias', 'Primeiro confira sintaxe, estrutura dos arquivos, IDs de elementos e contratos entre funções. Parser detecta erros de linguagem, não valida diversão ou regras. Depois execute. Teste incluir deliberadamente uma referência inexistente numa cópia de teste para confirmar que o mecanismo de diagnóstico realmente detecta falhas.', []),
  ('smoke', 'Teste de inicialização não é teste completo', 'smoke inicializacao console runtime tela branca', 'Abra o artefato no ambiente de destino e capture erros de console e exceções. Verifique que a cena inicial existe e aceita uma ação básica. Uma inicialização sem erro é só um smoke test. Ainda é necessário verificar regras, derrota, vitória e reinício; não marque o projeto completo apenas porque renderizou.', []),
  ('e2e', 'Roteiro funcional de uma partida completa', 'e2e teste funcional jogar vencer perder reiniciar validar', 'Execute: abrir, iniciar, mover, interagir, pontuar, receber dano, pausar, retomar, terminar e reiniciar. Para cada ação anote estado esperado e observado. Se houver aleatoriedade, use semente ou fixture controlada. Teste também uma ação inválida. Salve evidência do resultado, não só a lista de passos.', []),
  ('debug', 'Depurar com reprodução mínima e evidência', 'bug depurar debugging erro causa stacktrace reproduzir', 'Registre passos de reprodução, estado inicial, erro e última alteração. Reduza o caso até isolar o subsistema responsável. Corrija uma hipótese por vez e compare antes/depois. Use logs curtos de estado e transição, não dumps de todo o projeto. Teste novamente o caso original após limpar qualquer instrumentação temporária.', []),
  ('regression', 'Correção mínima com teste de regressão', 'regressao correcao patch preservar comportamento teste', 'Antes de corrigir, defina um caso que falha por causa do defeito. Faça a menor mudança que resolve a causa, então repita esse caso e um fluxo vizinho relevante. Preserve o teste quando ele protege comportamento importante. Registre como não verificado o que não pôde ser executado; não transforme expectativa em evidência.', []),
  ('assets', 'Assets rastreáveis e caminhos portáveis', 'assets imagens fontes audio licenca caminhos recurso', 'Registre origem, permissão de uso aplicável e atribuição necessária de cada recurso externo; prefira recursos próprios quando não houver autorização clara. Padronize nomes e teste diferenças de maiúsculas/minúsculas. Para prévia offline, embuta ou substitua recursos externos. Valide carregamento com rede desativada e pacote em outra pasta.', []),
  ('delivery', 'Entrega reproduzível com limites explícitos', 'entrega build exportar pacote readme publicar', 'Entregue os arquivos completos e instruções curtas de execução, controles, versão do ambiente e testes realmente feitos. Liste dependências e limitações conhecidas. Abra a cópia entregue, não apenas a pasta de desenvolvimento. Para mudanças, mantenha a versão anterior e descreva o comportamento alterado. Não afirme que foi publicado ou executado sem evidência.', []),
 ]),
 ('motores', 'Motores, 3D e rede', 'Fundamentos de Godot, Unity, física 3D, multiplayer e exportação.', [
  ('godot', 'Godot: composição de nós e cenas', 'godot gdscript nodes scenes nos cenas motor engine', 'No Godot, componha comportamentos com árvores de nós e transforme conjuntos reutilizáveis em cenas. Um personagem pode reunir corpo, sprite, câmera e forma de colisão. Defina a cena principal e confira a versão instalada antes de escrever APIs específicas. Teste a cena isolada e depois a execução do projeto.', ['nodes']),
  ('signals', 'Godot: sinais para comunicação entre cenas', 'godot signal sinais eventos interface vida hud', 'Emita sinais para comunicar fatos como vida alterada ou item coletado, permitindo que HUD e áudio reajam sem acoplamento desnecessário. Conecte cada consumidor uma vez e gerencie seu ciclo de vida. Teste uma coleta produzir um único sinal e sair da cena sem chamadas a objetos removidos.', ['signals']),
  ('character', 'Godot: CharacterBody e movimento controlado', 'godot characterbody2d characterbody3d move_and_slide fisica', 'Use CharacterBody para personagens controlados por código e configure formas e máscaras de colisão. Atualize movimento no ciclo de física apropriado à versão e consulte a assinatura de move_and_slide; não misture exemplos de Godot 3 e 4. Teste chão, paredes, inclinações e movimento em velocidades diferentes.', ['body']),
  ('unity', 'Unity: pool com estado restaurado e versão fixada', 'unity csharp objectpool gameobject prefab motor', 'Fixe a versão do Unity e dos pacotes do projeto antes de copiar APIs. UnityEngine.Pool oferece reutilização de objetos; configure criação, obtenção, devolução e destruição conforme a API instalada. Limpe estado, eventos e efeitos ao devolver instâncias. Teste reutilização e limite do pool em um build, não apenas no Editor.', ['pool']),
  ('collision3d', '3D: volumes de colisão e custo de precisão', '3d colisao esfera aabb bounding box raycast', 'Use volumes simples, como caixas e esferas, quando forem adequados ao comportamento esperado. Separe fase ampla de candidatos da verificação precisa; caixas alinhadas aos eixos podem ficar imprecisas para objetos girados. Teste escala, rotação e objetos rápidos. Não use a complexidade visual da malha como exigência automática da colisão.', ['3d']),
  ('multiplayer', 'Multiplayer: autoridade, validação e desconexão', 'multiplayer rede servidor autoridade rpc online sincronizacao', 'Em partidas competitivas, atribua ao servidor as decisões autoritativas relevantes e valide ações recebidas. Não confie em vida ou placar enviados pelo cliente. Planeje latência, entrada tardia e desconexão. No Godot, confirme configuração de autoridade e RPC na versão utilizada. Teste dois clientes reais com atraso; uma simulação local única não valida a rede.', ['network']),
  ('export', 'Exportação de motor e validação no destino', 'godot unity exportacao build plataforma executavel templates', 'No Godot, configure um preset de exportação e os templates compatíveis antes de gerar o pacote. Exporte para a plataforma escolhida e teste o resultado com seus recursos incluídos. Outros motores têm requisitos próprios. Um script solto não é um jogo exportado; informe quando editor, SDK ou ferramenta necessária não estiver disponível.', ['export']),
 ]),
]

memories = []
def add(mid, title, tags, content, refs=(), parent=None):
    normalized = unicodedata.normalize('NFKD', tags).encode('ascii', 'ignore').decode().split()
    relations = [parent] if parent else []
    memories.append(dict(id=mid, scope='global', title=title, content=content,
        tags=list(dict.fromkeys(['biblioteca-jogos-v1'] + normalized)),
        source='Aurora Jogos v1 · curadoria técnica, 2026-09-20; procedimento de referência, não execução comprovada.' + (' Referências: ' + ' | '.join(SOURCES[k] for k in refs) if refs else ' Orientação autoral de engenharia e validação.'),
        relations=relations, relationTypes={parent:'belonging'} if parent else {}))

add('jogos-root', 'Jogos — índice de conhecimento consultável', 'jogos desenvolvimento game gamedev criar jogo',
    'Biblioteca inicial de desenvolvimento de jogos: planejamento, arquitetura, movimento, mecânicas, mundo e IA, apresentação, dados, testes e motores. Consulte o tema específico da tarefa; não carregue todas as notas nem confunda orientação com experiência validada. Para um jogo novo, defina objetivo e controles, faça uma versão pequena jogável, teste e evolua. Esta biblioteca não cobre todo o domínio e deve crescer com correções comprovadas.')
for gid, title, description, rows in GROUPS:
    add('jogos-'+gid, 'Jogos — '+title, 'jogos '+gid,
        description + ' Este nó organiza procedimentos detalhados relacionados. Recupere somente os tópicos exigidos pelo pedido e transforme suas verificações em testes do projeto atual. Nenhuma nota desta coleção, por si só, comprova a execução de um jogo.', parent='jogos-root')
    for mid, title, tags, content, refs in rows:
        add('jogos-'+gid+'-'+mid, title, gid+' '+tags, content, refs, 'jogos-'+gid)

by_id = {m['id']:m for m in memories}
LINKS = [
 ('planejamento-vertical','qualidade-e2e'),('planejamento-todo','qualidade-regression'),('planejamento-reuse','planejamento-learning'),
 ('planejamento-acceptance','qualidade-e2e'),('planejamento-harness','dados-save'),
 ('arquitetura-loop','movimento-delta'),('arquitetura-state','movimento-visibility'),('arquitetura-input','movimento-touch'),
 ('arquitetura-reset','qualidade-regression'),('arquitetura-events','motores-signals'),('arquitetura-config','mecanicas-progression'),
 ('movimento-delta','movimento-fixed'),('movimento-vectors','mundo-camera'),('movimento-aabb','mecanicas-projectiles'),
 ('movimento-jump','movimento-aabb'),('movimento-touch','apresentacao-responsive'),
 ('mecanicas-damage','arquitetura-state'),('mecanicas-projectiles','dados-pool'),('mecanicas-score','arquitetura-reset'),
 ('mecanicas-pong','movimento-aabb'),('mecanicas-snake','mundo-spawn'),('mecanicas-puzzle','arquitetura-state'),
 ('mundo-camera','apresentacao-dpi'),('mundo-tiles','mundo-astar'),('mundo-enemy','mundo-astar'),
 ('mundo-procedural','qualidade-e2e'),('mundo-checkpoint','dados-save'),('mundo-spawn','dados-profile'),
 ('apresentacao-visual','apresentacao-accessibility'),('apresentacao-sprites','movimento-delta'),
 ('apresentacao-feedback','apresentacao-audio'),('apresentacao-responsive','apresentacao-dpi'),
 ('dados-save','dados-schema'),('dados-data','dados-schema'),('dados-profile','dados-canvas'),
 ('dados-pool','dados-cleanup'),('qualidade-syntax','qualidade-smoke'),('qualidade-debug','qualidade-regression'),
 ('qualidade-assets','planejamento-harness'),('qualidade-delivery','motores-export'),
 ('motores-godot','motores-character'),('motores-godot','motores-signals'),('motores-unity','dados-pool'),
 ('motores-collision3d','movimento-fixed'),('motores-multiplayer','dados-schema'),
]
for origin, target in LINKS:
    m = by_id['jogos-'+origin]
    target = 'jogos-'+target
    assert target in by_id and target != m['id']
    if target not in m['relations']:
        m['relations'].append(target)
        m['relationTypes'][target] = 'thematic'

assert len(memories) == 73 and len(by_id) == len(memories)
assert all(len(m['content']) < 700 for m in memories)
payload = dict(format='harness-aurora-memories', version=1, pack='aurora-jogos-v1', curatedAt='2026-09-20', memories=memories)
directory = ROOT / 'knowledge'
directory.mkdir(exist_ok=True)
target = directory / 'jogos-v1.json'
target.write_text(json.dumps(payload, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
print(json.dumps({'file':str(target),'memories':len(memories),'relations':sum(len(m['relations']) for m in memories),'contentChars':sum(len(m['content']) for m in memories)},ensure_ascii=False))
